(() => {
'use strict';
function fitDesktopPreview(){const scale=window.innerWidth>=1280?Math.max(1,Math.min(1.5,(window.innerHeight-96)/844)):1;document.documentElement.style.setProperty('--preview-scale',String(scale));}
fitDesktopPreview();window.addEventListener('resize',fitDesktopPreview);

document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role=button][data-action]')){e.preventDefault();e.target.click();}});
const KEY='czl-app3-camera-v1', TODAY='2026-09-23', IMAGE=window.CAMERA_IMAGE;
const HEALTH_BADGE=(()=>{const template=document.createElement('template');template.innerHTML=window.CAMERA_ORIGINAL.health;return template.content.querySelector('.health-risk-summary-badge')?.getAttribute('src')||'';})();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={calendar:'M8 3v4m8-4v4M4 6h16v15H4zM4 11h16M8 15h2m4 0h2m-8 3h2',file:'M6 3h8l4 4v14H6zM14 3v5h5M9 12h6m-6 4h4',family:'M10 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0M16 5a3 3 0 0 1 0 6M2 21v-3a5 5 0 0 1 10 0v3m3-7a5 5 0 0 1 5 5v2',headset:'M4 14v-3a8 8 0 0 1 16 0v3M4 12H2v7h4v-7zm16 0h2v7h-4v-7zm0 7v2h-6',help:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3h.01',chat:'M3 4h18v14H8l-5 3z',bag:'M3 7h18v14H3zM8 7V3h8v4',phone:'M7 3h10v18H7zM12 17h.01',quality:'M4 4h16v16H4zM7 8v8m4-8v8m-4-4h4m3-4h2l1 1v6l-1 1h-2z',cloud:'M6 18a4 4 0 0 1-1-8 7 7 0 0 1 13-2 5 5 0 0 1 0 10H6',share:'M12 16V3m-5 5 5-5 5 5M5 13v8h14v-8',home:'M3 10 12 3l9 7v10H5V10m4 10v-7h6v7',life:'M4 5h16v14H4zM8 9h8m-8 4h5',ai:'M12 3v3m-7 2h14v11H5zM9 12h.01M15 12h.01M9 16h6',care:'M12 20S3 15 3 9a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 6-9 11-9 11',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21a8 8 0 0 1 16 0',back:'m14 5-7 7 7 7',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zm5 3h4',plus:'M12 5v14M5 12h14',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1zM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',camera:'M3 7h5l2-3h4l2 3h5v13H3zM16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',video:'M3 6h12v12H3zm12 4 6-3v10l-6-3',expand:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',more:'M5 12h.01M12 12h.01M19 12h.01',play:'m8 4 12 8-12 8z',image:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M16 7h.01',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6',leaf:'M19 4C7 1 2 8 6 15s15 3 13-11ZM5 21l11-13',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1',activity:'M2 12h5l3-8 4 16 3-8h5',temp:'M9 14V5a3 3 0 0 1 6 0v9a5 5 0 1 1-6 0M12 9v9',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 6v6l4 2',lock:'M6 10h12v11H6zM8 10V6a4 4 0 0 1 8 0v4',wifi:'M2 8a17 17 0 0 1 20 0M5 12a12 12 0 0 1 14 0M8 16a6 6 0 0 1 8 0M12 20h.01',close:'m6 6 12 12M6 18 18 6',check:'m4 12 5 5L20 6'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.camera}"/></svg>`;
const btn=(label,act,cls='primary',attrs='')=>`<button type="button" class="${cls}" data-action="${act}" ${attrs}>${label}</button>`;
const ib=(name,label,act,attrs='')=>btn(icon(name),act,'icon-btn',`aria-label="${label}" ${attrs}`);
const tag=(t,c='')=>`<span class="tag ${c}">${esc(t)}</span>`;
const empty=(title,text,action='',name='camera')=>`<div class="card empty">${icon(name)}<h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;
const row=(label,value,action,name='settings',attrs='')=>btn(`${icon(name)}<span class="label">${label}</span><span class="value">${esc(value)}</span><span class="caret">›</span>`,action,'link-row',attrs);
const dateLabel=d=>d===TODAY?'今天':d;
const clone=v=>JSON.parse(JSON.stringify(v));
function makeDevice(id,name,petId,member=true){return {id,name,petId,online:true,lastSeen:'2026-09-23 09:40',role:'owner',subscription:member?'active':'inactive',privacy:false,quality:'高清',sd:true,analysis:'ready',media:[],shared:[],firmware:'1.0.3',network:'家庭 Wi-Fi'};}
function seed(){const d1=makeDevice('cam-1','Mochi 的雨林箱','pet-1'),d2=makeDevice('cam-2','书房爬宠箱','pet-2');
return {version:1,devices:[d1,d2],pets:[{id:'pet-1',name:'Mochi',species:'绿鬣蜥'},{id:'pet-2',name:'小绿',species:'绿鬣蜥'}],events:[{id:'event-1',deviceId:'cam-1',petId:'pet-1',type:'activity',title:'活动较平时减少',time:TODAY+' 08:40',read:false,resolved:false,detail:'07:00–08:30 的活动时长低于最近 7 日同时间段。请结合画面与日常状态继续观察。',evidence:'08:15–08:30'}],reports:[{id:'report-1',deviceId:'cam-1',petId:'pet-1',date:TODAY,food:'08:12',water:'13:20',activity:80,molt:false,region:[1,1,2,1,2,4,1,2,3],healthScore:95,risk:'clear'},{id:'report-2',deviceId:'cam-1',petId:'pet-1',date:'2026-09-22',food:'08:30',water:'12:40',activity:95,molt:false,region:[1,1,2,1,2,4,1,2,3],healthScore:95,risk:'clear'},{id:'report-3',deviceId:'cam-2',petId:'pet-2',date:TODAY,food:'08:45',water:'12:50',activity:95,molt:false,region:[1,1,2,1,2,4,1,2,3],healthScore:95,risk:'clear'},{id:'report-4',deviceId:'cam-2',petId:'pet-2',date:'2026-09-22',food:'08:20',water:'12:30',activity:85,molt:false,region:[1,1,2,1,2,4,1,2,3],healthScore:95,risk:'clear'}]};}
let db;try{db=JSON.parse(localStorage.getItem(KEY));if(db?.version!==1||!Array.isArray(db.devices)||!Array.isArray(db.pets)||!Array.isArray(db.events)||!Array.isArray(db.reports))db=seed();}catch{db=seed();}
db.devices.forEach(d=>{delete d.shareLink;});
let snapshotNotice=null;
let view={page:'home',deviceId:db.devices[0]?.id||'',section:'care',date:TODAY},stack=[],modal=null,wizard=null,recording=null,connectTimer=null,toastTimer=null,scenario='normal',storageFailed=false;
const dev=()=>db.devices.find(d=>d.id===view.deviceId),pet=id=>db.pets.find(p=>p.id===id),pname=id=>pet(id)?.name||'未关联宠物';
const currentReport=()=>db.reports.find(r=>r.deviceId===view.deviceId&&r.date===view.date&&r.petId===dev()?.petId);
const reportById=id=>db.reports.find(r=>r.id===id);
const visibleEvents=d=>db.events.filter(e=>e.deviceId===d.id&&e.type!=='environment');
const pending=d=>visibleEvents(d).filter(e=>!e.resolved);
const dayEvents=(d,date)=>pending(d).filter(e=>e.time.startsWith(date));
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));storageFailed=false;}catch{storageFailed=true;}$('#save-status').textContent=storageFailed?'浏览器限制存储，本次仍可继续体验。':'演示数据已保存在当前浏览器';}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2500);}
function isOwner(d=dev()){return d?.role==='owner';}
function canManage(){if(!isOwner()){toast('共享成员仅可查看，请联系设备拥有者');return false;}return true;}
function canLive(){const d=dev();if(!d?.online||d.privacy){toast(d?.privacy?'隐私模式已开启':'设备离线，实时操作不可用');return false;}return true;}
function stopRecording(){if(recording){const d=db.devices.find(d=>d.id===recording.deviceId);if(d)d.media.unshift({id:'media-'+Date.now(),kind:'录像',time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),duration:Math.max(1,Math.round((Date.now()-recording.start)/1000))});recording=null;save();}}
function go(page,extra={},push=true){snapshotNotice=null;if(recording&&page!=='camera')stopRecording();if(push)stack.push({...view,scroll:$('#app-content').scrollTop});view={...view,page,...extra,scroll:0};closeModal(false);render();}
function back(){snapshotNotice=null;if(wizard){if(wizard.step==='connecting'){clearTimeout(connectTimer);wizard.step=2;render();return;}if(wizard.step>0){wizard.step-=1;render();return;}openModal('cancel-bind');return;}stopRecording();view=stack.pop()||{page:'home',deviceId:db.devices[0]?.id||'',section:'care',date:TODAY};closeModal(false);render();}
function root(page){snapshotNotice=null;stopRecording();stack=[];view={...view,page,scroll:0,context:null};closeModal(false);render();}
const names={home:'H01 · 首页',camera:'C01 · 摄像头',messages:'M01 · 消息',event:'E01 · 事件详情',report:'A02 · 行为详情',health:'A04 · 健康详情',history:'A03 · 历史报告',playback:'V02 · 录像回看',album:'V03 · 相册',settings:'S01 · 设备设置',subscription:'B01 · 摄像头订阅',subscriptions:'B02 · 设备订阅',pets:'P01 · 宠物档案',assistant:'G01 · 管家',life:'生活',care:'趣养',mine:'我的',add:'D01 · 添加设备'};
function render(){
const d=dev(),global=['home','life','assistant','care','mine'].includes(view.page);if(!d&&['camera','settings','playback','album','subscription','history'].includes(view.page)){view.page='home';return render();}
let header;
if(view.page==='home')header=`<div class="topbar"><div class="title">早上好<small>今日有 ${db.devices.reduce((n,x)=>n+pending(x).length,0)} 条提醒 · AI 养宠管家</small></div>${ib('bell','消息','messages')}${ib('plus','添加设备','add')}</div>`;
else if(view.page==='mine')header=`<div class="topbar"><div class="title">我的</div><span class="mine-bell" aria-label="消息">${icon('bell')}</span></div>`;
else if(view.page==='camera')header=`<div class="topbar">${ib('back','返回','back')}<div class="title">${btn(esc(d.name)+' ⌄','switch-device','',`aria-label="切换设备：${esc(d.name)}"`)}<small>${esc(pname(d.petId))} · ${d.role==='viewer'?'共享查看':'我的摄像头'}</small></div>${ib('settings','设备设置','settings')}</div><nav class="section-tabs" aria-label="摄像头栏目">${['care','companion'].map((section,i)=>btn(['视频直播','智能养护'][i],'section',view.section===section?'active':'',`data-value="${section}" aria-pressed="${view.section===section}"`)).join('')}</nav>`;
else header=`<div class="topbar">${!global||view.context?ib('back','返回','back'):''}<div class="title">${esc(wizard?'添加爬宠摄像头':(view.page==='playback'?(view.source==='cloud'?'云回放':'本地回放'):view.page==='report'?({food:'饮食',activity:'活动',molt:'蜕皮'}[view.kind]||'行为详情'):(names[view.page]||'').split(' · ').pop()))}</div>${view.page==='messages'?btn('全部已读','read-all','text-btn'):''}${wizard?btn('取消','cancel-bind','text-btn'):''}</div>`;
$('#app-header').innerHTML=header;
const pages={home:homePage,camera:cameraPage,messages:messagesPage,event:eventPage,report:reportPage,health:healthPage,history:historyPage,playback:playbackPage,album:albumPage,settings:settingsPage,subscription:subscriptionPage,subscriptions:subscriptionsPage,pets:petsPage,assistant:assistantPage,life:()=>boundaryPage('生活','宠友社区、内容发布与评价沿用 APP 3.0。本次接入原型不展开社区流程。','life'),care:()=>boundaryPage('趣养','问诊与养宠工具沿用 APP 3.0。摄像头分析结果通过“问问管家”继续解读。','care'),mine:minePage,add:wizardPage};
$('#app-content').innerHTML=(pages[view.page]||homePage)();$('#app-content').scrollTop=view.scroll||0;
$('#app-nav').innerHTML=global?`<div class="nav-tabs">${[['home','首页','home'],['life','生活','life'],['assistant','管家','ai'],['care','趣养','care'],['mine','我的','user']].map(([p,t,i])=>btn((i==='ai'?'<span class="ai-orb">AI</span>':icon(i))+`<span>${t}</span>`,'root',view.page===p?'active':'',`data-value="${p}" ${view.page===p?'aria-current="page"':''}`)).join('')}</div>`:'';
renderScenarios();save();
}
function eventsHtml(items){return items.map(e=>btn(`<span class="event-mark">${icon('activity')}</span><span class="grow"><strong>${esc(e.title)} ${e.read?'':'<span class="tag red">未读</span>'}</strong><small>${esc(pname(e.petId))} · ${esc(e.time.slice(11))} · ${e.resolved?'已解除':'待关注'}</small></span><span class="caret">›</span>`,'event','event-row',`data-id="${e.id}"`)).join('');}
function deviceCard(d){
 const species=pet(d.petId)?.species||(d.petId?'待完善':'待关联');
 return `<button type="button" class="device-card" data-action="open-device" data-id="${d.id}" aria-label="${esc(d.name)}，${esc(pname(d.petId))}，${d.online?'在线':'离线'}" title="${esc(d.name)}">
 <div class="device-card-head"><span class="device-avatar">${d.privacy?icon('shield'):`<img src="${IMAGE}" alt="${esc(d.name)}设备缩略图">`}</span><span class="device-heading"><strong class="device-name">${esc(d.name)}</strong><span class="device-connection ${d.online?'':'offline'}"><i></i>${d.online?'在线':'离线'}</span></span></div>
 <div class="device-species-row"><span>爬宠品种</span><strong title="${esc(species)}">${esc(species)}</strong></div>
 </button>`;
}
function homePage(){const alerts=db.devices.flatMap(pending);return `${alerts.length?`<div class="card alert-card"><div class="row between"><h3>重要提醒</h3>${tag(alerts.length+' 条','amber')}</div>${eventsHtml(alerts)}</div>`:''}<div class="row between" style="margin-top:20px"><h2>我的设备</h2>${btn('＋ 添加','add','text-btn')}</div>${db.devices.length?`<div class="device-grid">${db.devices.map(deviceCard).join('')}</div>`:empty('还没有设备','添加爬宠摄像头，开始了解它的日常。',btn('添加设备','add'))}<div class="card"><h3>智能待办</h3><p class="muted">暂无待办</p></div>`;}
function liveVideo(d){let blocked=!d.online||d.privacy;return `<div class="video">${!blocked?`<img src="${IMAGE}" alt="爬宠箱示例直播画面"><div class="video-top">${tag('● 在线')}<span class="camera-quality">${esc(d.quality)}</span></div><span class="video-bottom">${TODAY} 09:41:00 ${recording?' · ● 录像中':''}</span>`:`<div class="video-cover">${icon(d.privacy?'shield':'wifi')}<strong>${d.privacy?'隐私模式已开启':'设备已离线'}</strong><p>${d.privacy?'实时画面与实时操作已暂停':'最后在线 '+esc(d.lastSeen)}</p>${d.privacy&&isOwner(d)&&d.online?btn('关闭隐私模式','privacy','secondary'):''}</div>`}</div>`;}
function cameraPage(){const d=dev();if(view.section==='companion')return companionPage(d);const disabled=!d.online||d.privacy||!isOwner(d);
const basic=(i,title,desc,action,tone,attrs='')=>btn(`<span class="camera-function-icon ${tone}">${icon(i)}</span><strong>${title}</strong><small>${desc}</small>`,action,'camera-function-card',attrs);
return `<div class="camera-player">${liveVideo(d)}${snapshotNotice===d.id&&d.online&&!d.privacy?`<div class="snapshot-feedback" role="status"><img src="${IMAGE}" alt="刚保存的截图预览"><span>截图已保存到相册</span>${btn('进入相册','album','primary')}</div>`:''}</div><div class="toolbar camera-quick-actions">${[['expand','全屏','fullscreen'],['camera','截图','snapshot'],['video',recording?'结束录像':'录像','record'],['quality','画质','quality']].map(([i,t,a])=>btn(`<span>${icon(i)}</span><b>${t}</b>`,a,'tool'+(a==='record'&&recording?' active':''),((a==='snapshot'||a==='record')&&disabled)||((a==='fullscreen'||a==='quality')&&(!d.online||d.privacy))||(a==='quality'&&!isOwner(d))?'disabled':'')).join('')}</div>
${d.subscription!=='active'?`<div class="live-membership-banner"><span class="live-membership-icon">${icon('shield')}</span><div><strong>开通设备会员</strong><p>解锁 AI 养护分析与云回放</p></div>${btn(isOwner(d)?'立即开通':'查看权益','subscription','live-membership-cta')}</div>`:''}
<div class="camera-function-grid">${basic('play','本地回放','查看存储卡录像','playback','blue','data-value="sd"')}${basic('cloud','云回放',d.subscription==='active'?'设备会员已开通':'需开通设备会员','playback','blue','data-value="cloud"')}${basic('image','相册','截图与录像 · '+d.media.length+' 项','album','cyan')}${basic('shield','隐私模式',d.privacy?'已开启':'已关闭','privacy','indigo',`aria-pressed="${d.privacy}" ${!d.online||!isOwner(d)?'disabled':''}`)}</div>

`; }
function companionHero(d){return `<div class="card hero"><h2>开启智能养护</h2><p>解锁行为记录、健康洞察与云端录像。</p>${btn(isOwner(d)?'开通会员':'查看设备权益','subscription','secondary')}</div>`;}

function originalContent(kind,petId){return `<div class="original-camera">${(window.CAMERA_ORIGINAL[kind]||'').replaceAll('{{PET}}',esc(pname(petId)))}</div>`;}
const SAMPLE_REPORT=Object.freeze({id:'sample',food:'08:12',water:'13:20',activity:80,molt:false,region:[1,1,2,1,2,4,1,2,3],healthScore:95,risk:'clear'});
function careData(d=dev(),r=currentReport(),sample=d.subscription!=='active'){
 const report=sample?{...SAMPLE_REPORT,deviceId:d.id,petId:d.petId,date:view.date}:r;
 const keys={food:'food',water:'water',activity:'activity',region:'region',molt:'molt',health:'healthScore',risk:'risk'};
 const states=Object.fromEntries(Object.entries(keys).map(([k,field])=>{const raw=report?.states?.[k];const explicit=raw==='pending'?'insufficient':raw;const global=['pending','insufficient'].includes(d.analysis)?'insufficient':null;return [k,sample?'ready':explicit&&explicit!=='ready'?explicit:global&&!explicit?global:report?.[field]!=null?'ready':'insufficient'];}));
 return {report,states,sample};
}
const stateLabel=()=> '数据不足';
function sampleMark(sample){return sample?tag('示例数据','gray'):'';}
function sampleBanner(){return `<div class="card sample-banner membership-placeholder"><div class="membership-placeholder-head"><span class="membership-placeholder-icon" aria-hidden="true">${icon('shield')}</span><div><strong>订阅设备会员</strong><p>解锁 AI 养护分析与云回放</p></div></div>${btn(isOwner()?'立即订阅':'查看设备会员','subscription','primary full')}<p class="membership-example-note">当前展示为示例数据，订阅后查看本设备的分析结果。</p></div>`;}
function careLink(label,kind,c){const keys=kind==='food'?['food','water']:[kind];const enabled=keys.some(k=>c.states[k]==='ready');return btn(label,kind==='health'?'health':'report','text-btn',`data-kind="${kind}" data-id="${c.report?.id||''}" data-sample="${c.sample}" ${enabled?'':'disabled'} aria-label="${label}${enabled?'':'，'+'数据不足'}"`);}
function careMetric(label,key,c){const state=c.states[key],value=state==='ready'?esc(c.report[key]):'—';return `<div class="care-metric" data-result="${key}" data-state="${state}"><span class="care-metric-title">${label}</span><span class="care-metric-recency">最近一次</span><strong>${value}</strong>${state!=='ready'?`<small>${'数据不足'}</small>`:''}</div>`;}
function analysisBody(d,r){if(!d.petId)return empty('先关联你的爬宠','直播与回放可正常使用。关联宠物后，再生成个体分析。',btn('关联宠物','link-pet','primary',!isOwner(d)?'disabled':''),'user');
 const c=careData(d,r),st=c.states,report=c.report,mark=sampleMark(c.sample);
 const allReady=['food','water','activity'].every(k=>st[k]==='ready');
 const summary=allReady?`${esc(pname(d.petId))} 的进食、饮水与活动记录已完成分析，整体表现稳定。建议结合日常观察持续关注饮食与活动变化。`:'进食、饮水或活动记录不足，暂无法形成完整的综合结论。';
 const healthReady=st.health==='ready',riskReady=st.risk==='ready';
 return `${c.sample?sampleBanner():''}<section class="care-today-group" aria-labelledby="care-today-title"><header class="care-today-heading"><h2 id="care-today-title">今日状态</h2></header><section class="card care-food" data-module="food"><div class="row between care-section-heading"><div class="care-heading-label"><h3>饮食分析</h3>${mark}</div>${careLink('查看详情','food',c)}</div><div class="care-food-grid">${careMetric('进食','food',c)}${careMetric('饮水','water',c)}</div></section>
 <section class="card care-activity" data-module="activity"><div class="row between care-section-heading"><div class="care-heading-label"><h3>活动分析</h3>${mark}</div>${careLink('查看详情','activity',c)}</div><div class="care-duration" data-result="activity" data-state="${st.activity}"><h3>今日活动</h3><strong>${st.activity==='ready'?durationValue(report.activity):'—'}</strong>${st.activity!=='ready'?`<small>${'数据不足'}</small>`:''}</div>${activityMap(report,st.region)}</section>
 <section class="card care-molt" data-module="molt"><div class="row between care-section-heading"><div class="care-heading-label"><h3>蜕皮检测</h3>${mark}</div>${careLink('查看详情','molt',c)}</div><div class="care-molt-result" data-result="molt" data-state="${st.molt}"><span class="care-molt-symbol" aria-hidden="true">${icon('shield')}</span><div class="care-molt-copy"><div class="care-molt-state-line"><strong>${st.molt==='ready'?'未蜕皮':'—'}</strong></div><p>${st.molt==='ready'?'未检测到蜕皮行为':'数据不足，暂无法判断蜕皮状态'}</p></div></div></section>
 <section class="card report-analysis" data-module="summary"><div class="care-section-heading"><div class="care-heading-label"><h3><span class="ai-chip">AI</span> 状态解读</h3>${mark}</div></div><p>${summary}</p></section></section>
 <section class="care-health-group" aria-labelledby="care-health-title"><header class="care-today-heading"><h2 id="care-health-title">健康评估</h2></header><section class="card care-health" data-module="health"><div class="care-section-heading"><div class="care-heading-label"><h3>AI 多维健康分析</h3>${mark}</div></div><div class="care-health-summary"><div><span class="tag ${healthReady?'':'gray'}">${healthReady?'优秀':'数据不足'}</span><p>${healthReady?'状态极佳，继续保持！':'数据不足，暂无法生成健康报告。'}</p></div><strong class="care-health-score">${healthReady?report.healthScore:'—'}${healthReady?'<small>分</small>':''}</strong></div>${careLink('查看健康报告','health',c)}</section>
 <section class="card care-risk" data-module="risk"><div class="care-section-heading"><div class="care-heading-label"><h3>异常疾病风险识别</h3>${mark}</div></div><div class="care-risk-overview"><strong class="care-risk-result ${riskReady?'ready':''}">${riskReady?'暂未识别到明显风险':'数据不足'}</strong>${riskReady?`<img class="care-risk-badge" src="${HEALTH_BADGE}" alt="" aria-hidden="true">`:''}</div><p>${riskReady?'当前状态良好，建议继续观察日常表现与体表变化。':'识别依据不足，不能据此判断是否存在风险。'}</p></section>
 <section class="card report-analysis" data-module="health-reading"><div class="care-section-heading"><div class="care-heading-label"><h3><span class="ai-chip">AI</span> 健康解读</h3>${mark}</div></div><p>${healthReady&&riskReady?`${esc(pname(d.petId))} 今日健康表现良好，活力、进食、体表与姿态均无明显异常。暂未发现卡皮或疑似疾病风险，建议持续关注食欲与蜕皮情况。`:'健康或风险识别数据不足，暂无法生成完整健康解读。'}</p></section></section>`;
}
function durationValue(minutes){const h=Math.floor(minutes/60),m=minutes%60;return `${h?h+'<small>小时</small>':''}${m||!h?m+'<small>分钟</small>':''}`;}
function activityMap(r,state='ready'){return `<div class="activity-area-card care-region" data-result="region" data-state="${state}"><div><h3>活动区域</h3><p>${state==='ready'?'今日活动集中在右侧区域':'活动区域数据不足'}</p><small>九宫格展示各区域活跃情况</small></div><div class="activity-heatmap ${state==='ready'?'':'heatmap-neutral'}" role="img" aria-label="${state==='ready'?'右侧区域更活跃':'暂无有效活动区域数据'}">${(state==='ready'?r.region:Array(9).fill(0)).map(n=>`<span class="heat-${n}"></span>`).join('')}</div></div>`;}
function companionPage(d){return analysisBody(d,currentReport());}
function detailReport(){return view.sample?{...SAMPLE_REPORT,petId:view.petId,deviceId:view.deviceId,date:view.sampleDate}:reportById(view.reportId);}
function healthPage(){const d=dev(),r=detailReport(),c=careData(d,r,!!view.sample);if(!r||c.states.health!=='ready')return empty('暂无法评估','健康数据不足，暂无法生成报告。');if(!view.sample&&d.subscription!=='active')return companionHero(d);const t=document.createElement('template');t.innerHTML=originalContent('health',r.petId);if(c.states.risk!=='ready'){const risk=t.content.querySelector('.health-risk-panel');risk.innerHTML=`<h3>异常疾病风险识别</h3><p>${stateLabel(c.states.risk)}，暂无法判断风险。</p>`;}return (view.sample?sampleBanner():'')+t.innerHTML;}
function messagesPage(){const all=db.devices.flatMap(visibleEvents);return `<p class="caption">打开详情即标记已读；已读不会解除异常。</p>${all.length?`<div class="card">${eventsHtml(all)}</div>`:empty('暂无消息','设备状态与异常提醒会出现在这里。','','bell')}`;}
function eventPage(){const e=db.events.find(e=>e.id===view.eventId);if(!e)return empty('事件不可用','设备可能已经移除。');const d=dev();return `<div class="card"><div class="row between">${tag('行为提醒','amber')}${tag(e.resolved?'已解除':'待关注',e.resolved?'green':'amber')}</div><h2 style="margin-top:14px">${esc(e.title)}</h2><p class="muted">${esc(d.name)} · ${esc(pname(e.petId))}<br>${esc(e.time)}</p><p>${esc(e.detail)}</p><p class="caption">已读 · 事件 ${esc(e.id)}</p></div><div class="card"><h3>观察依据</h3><p>分析时段：${esc(e.evidence)}。可查看相应录像片段辅助判断。</p>${btn('查看对应录像','event-evidence','secondary full')}</div>${btn('问问管家','ask-event','primary full')}${isOwner(d)&&!e.resolved?btn('记录为已处理','resolve-event','secondary full'):''}<p class="caption" style="margin-top:12px">“已处理”记录用户处理结果；原型以“已解除”演示闭环。</p>`;}
const kinds={food:{title:'饮食记录',ob:r=>'最近一次识别到进食：'+r.food,time:'08:12–08:16',suggestion:'结合食物消耗与日常喂养记录观察食欲变化。',unit:'次',values:[2,2,1,2,2,1,1]},activity:{title:'活动分析',ob:r=>'累计识别活动 '+r.activity+' 分钟',time:'07:00–09:30',suggestion:'对照最近几天同一时段的活动，结合画面继续观察。',unit:'分钟',values:[95,110,90,100,85,95,80]},molt:{title:'蜕皮观察',ob:()=> '当前时段未检测到蜕皮行为',time:'00:00–09:30',suggestion:'“未检测到”不等于确认没有蜕皮，可结合体表观察补充记录。',unit:'',values:[]}};
function reportWeek(r,selected){const anchor=new Date(selected+'T12:00:00');const end=new Date(anchor.getTime()+(6-(anchor.getDay()+6)%7)*86400000);const days=Array.from({length:7},(_,i)=>{const day=new Date(end.getTime()-(6-i)*86400000);return {date:day.toISOString().slice(0,10),label:(day.getMonth()+1)+'.'+day.getDate(),week:['日','一','二','三','四','五','六'][day.getDay()]};});return `<section class="card report-date-panel"><div class="row between"><div><span class="eyebrow">${esc(pname(r.petId))} · ${kinds[view.kind].title}</span><h3>${days[0].label} — ${days[6].label}</h3></div><label class="report-calendar" aria-label="选择报告日期"><input type="date" aria-label="选择报告日期" max="${TODAY}" value="${esc(selected)}" data-change="report-date"></label></div><div class="report-week">${days.map(day=>btn(`<span>周${day.week}</span><strong>${day.label}</strong>`,'report-day',day.date===selected?'active':'',`data-value="${day.date}" aria-pressed="${day.date===selected}" ${day.date>TODAY?'disabled':''}`)).join('')}</div></section>`;}
function reportPage(){const original=detailReport(),d=dev();if(!original)return empty('报告不可用','请返回选择其他记录。');if(!view.sample&&d.subscription!=='active')return companionHero(d);const selected=view.reportDate||original.date,r=view.sample?(selected===original.date?original:null):db.reports.find(x=>x.deviceId===d.id&&x.petId===original.petId&&x.date===selected),calendar=view.kind==='molt'?'':reportWeek(original,selected),banner=view.sample?sampleBanner():'';if(!r)return banner+calendar+empty('当天暂无报告','当前日期数据不足，可选择其他日期。','','clock');const c=careData(d,r,!!view.sample);const valid=view.kind==='food'?c.states.food==='ready'||c.states.water==='ready':c.states[view.kind]==='ready';if(!valid)return banner+calendar+empty('暂无法查看详情',stateLabel(c.states[view.kind]));
 const t=document.createElement('template');t.innerHTML=originalContent(view.kind,r.petId);
 if(view.kind==='food'){
 ['food','water'].forEach((key,i)=>{const ready=c.states[key]==='ready',card=t.content.querySelectorAll('.food-summary-card')[i],event=t.content.querySelectorAll('.food-event-item')[i];card.querySelector('p').textContent=ready?'最近一次 '+r[key]:stateLabel(c.states[key]);if(!ready){card.querySelector('strong').textContent='—';event.hidden=true;}else{event.querySelector('.food-event-copy p span').textContent=r[key];}});
 if(c.states.food!=='ready'||c.states.water!=='ready'){t.content.querySelector('.food-habit-head>span')?.remove();t.content.querySelector('.today-habit-analysis').innerHTML='<p>记录尚不完整，暂无法形成综合饮食结论。</p>';}
 }else if(view.kind==='activity'){t.content.querySelector('.food-summary-card>strong').innerHTML=durationValue(r.activity);}
 t.content.querySelectorAll('.food-event-item:not([hidden])').forEach((event,i)=>{const thumb=event.querySelector('.food-event-thumb');if(!thumb)return;const time=event.querySelector('.food-event-copy p span')?.textContent||'',title=event.querySelector('.food-event-copy h3')?.textContent||'事件片段';const button=document.createElement('button');button.type='button';button.className='event-clip-thumb';button.dataset.action='event-clip';button.dataset.time=time;button.dataset.title=title;button.dataset.date=selected;button.dataset.petId=r.petId;button.setAttribute('aria-label',`播放 ${time} ${title}`);thumb.replaceWith(button);button.append(thumb);const overlay=document.createElement('span');overlay.className='event-clip-play';overlay.innerHTML=icon('play');button.append(overlay);});
 return banner+calendar+t.innerHTML;}
function historyPage(){const reports=db.reports.filter(r=>r.deviceId===view.deviceId);return reports.length?`<p class="caption">报告保留生成时的宠物归属。</p><div class="card">${reports.map(r=>row(`${esc(r.date)}<small>${esc(pname(r.petId))} · 行为报告</small>`,'查看','report','clock',`data-id="${r.id}" data-kind="activity"`)).join('')}</div>`:empty('暂无历史报告','积累足够的分析数据后，报告会保存在这里。','','clock');}
function playbackPage(){const d=dev(),source=view.source||'sd',cloud=source==='cloud',canPlay=cloud?d.subscription==='active':(d.online&&d.sd);let state=view.playbackState||'ready';let message='';if(cloud&&d.subscription!=='active')message='云回放需开通设备会员';else if(!cloud&&!d.online)message='设备离线，无法读取存储卡';else if(!cloud&&!d.sd)message='未检测到存储卡';else if(view.playDate&& ![TODAY,'2026-09-22'].includes(view.playDate))state='empty';
return `<div class="datebar"><label for="play-date">日期</label><input id="play-date" type="date" max="${TODAY}" value="${esc(view.playDate||view.date)}" data-change="play-date">${!cloud&&canPlay?'<span class="playback-storage-inline" aria-label="存储空间已用 42.6 GB，总容量 128 GB">42.6 / 128 GB</span>':''}</div>${message?empty(message,cloud?'为当前摄像头开通设备会员后，即可查看云端录像。':'请确认设备在线且已插入可用存储卡。',cloud?btn(isOwner(d)?'开通设备会员':'查看设备会员','subscription'):'','play'):state==='empty'?`<div class="video playback-empty"><div class="video-cover">${icon('video')}<strong>当天没有录像</strong><p>${esc(view.playDate||view.date)} · 暂无录像片段</p></div><div class="video-top">${tag(cloud?'云录像':'存储卡')}</div></div><div class="row between" style="margin-top:10px">${btn(icon('play')+'播放','toggle-play','secondary','disabled')}${btn(esc(view.speed||'1.0')+'×','speed','secondary','disabled')}</div>`:state==='error'?empty('录像加载失败','网络请求未成功，可重试加载。',btn('重新加载','retry-playback'),'wifi'):`<div class="video"><img src="${IMAGE}" alt="历史录像示例帧"><div class="video-top">${tag(cloud?'云录像':'存储卡')}<span>${view.playing?'播放中 · 模拟':'已暂停'}</span></div><span class="video-bottom">${esc(view.playDate||view.date)} ${esc(view.segment||'08:12')} · 示例录像</span></div><div class="row between" style="margin-top:10px">${btn(icon('play')+(view.playing?'暂停':'播放'),'toggle-play','secondary')}${btn(esc(view.speed||'1.0')+'×','speed','secondary')}</div><div class="card"><h3>可播放时段</h3><div class="timeline">${['07:30','08:12','08:40','09:00'].map(t=>btn(t,'segment',(view.segment||'08:12')===t?'selected':'',`data-value="${t}"`)).join('')}</div></div>`}${canPlay?'':'<p class="caption">当前页面仅展示所选回放类型。</p>'}`;}
function albumPage(){const d=dev();return d.media.length?`<p class="caption">${esc(d.name)} · ${d.media.length} 项，仅当前浏览器演示</p><div class="gallery">${d.media.map(m=>btn(`<img src="${IMAGE}" alt="${esc(m.kind)}预览"><p>${esc(m.kind)} ${esc(m.time)}${m.duration?' · '+m.duration+'秒':''}</p>`,'media','',`data-id="${m.id}"`)).join('')}</div>`:empty('相册还是空的','在视频直播中截图或录制，完成后即可在这里查看。','','image');}

function settingsPage(){const d=dev();return `${!isOwner(d)?'<p class="caption">共享成员只读。设备管理、截图录像与订阅开通由拥有者操作。</p>':''}<div class="card">${row('设备名称',d.name,'rename')}${row('关联宠物',pname(d.petId),'link-pet','user')}${row('网络状态',d.online?d.network:'离线','network','wifi')}${row('存储卡',d.sd?'42.6 GB / 128 GB':'未插入','storage','video')}${row('固件版本',d.firmware,'firmware')}${row('设备信息',d.id,'device-info','camera')}</div>${btn(isOwner(d)?'移除设备':'停止接收共享','remove-device','danger full')}<p class="caption">移除操作在原型中可通过场景重置恢复。</p>`;}
function subscriptionPage(){const d=dev();return `<div class="card subscription">${tag('摄像头独立订阅')}<h2 style="margin-top:16px">更懂它的每一天</h2><p>购买对象：${esc(d.name)}<br>设备编号：${esc(d.id)}</p><div class="plan-price">${d.subscription==='active'?'权益已生效':'AI 分析 + 云录像'}</div><p>套餐价格与云存储时长待业务确认</p></div><div class="card"><h3>此设备专属权益</h3><p>✓ 进食、活动与蜕皮行为分析<br>✓ 历史报告与 AI 解读<br>✓ 云端录像回看</p><div class="separator"></div><p>基础直播和存储卡回放不依赖本订阅。</p></div>${d.subscription==='active'?tag('当前设备已开通','green'):isOwner(d)?btn('模拟开通当前设备','activate','primary full'):empty('由拥有者管理订阅','共享成员不能购买或变更设备权益。','','lock')}<p class="caption" style="margin-top:14px">仅演示权益状态，不发起支付，不自动续费，不代表正式套餐承诺。</p>`;}
function subscriptionsPage(){return db.devices.length?db.devices.map(d=>`<div class="card"><h3>${esc(d.name)}</h3><p>${d.subscription==='active'?'AI 分析与云录像 · 已开通':'尚未开通'} · ${isOwner(d)?'拥有者':'共享成员'}</p>${btn('查看设备权益','device-subscription','text-btn',`data-id="${d.id}"`)}</div>`).join(''):empty('暂无设备订阅','先添加摄像头，再为设备开通权益。');}
function minePage(){const tile=(i,label,tone='')=>`<div class="mine-function"><span class="mine-function-icon ${tone}">${icon(i)}</span><span>${label}</span></div>`;return `<div class="mine-page"><div class="mine-profile"><span class="mine-avatar">基</span><div><h2>叶仲基</h2><p>宠主ID CZL10284956</p></div></div><div class="mine-shortcuts"><section class="card mine-shortcut"><h3>宠物档案</h3><p>记录每一次成长</p><span class="mine-shortcut-icon blue">${icon('bag')}</span></section><section class="card mine-shortcut"><h3>设备管理</h3><p>绑定、设置与会员</p><span class="mine-shortcut-icon green">${icon('phone')}</span></section></div><section class="mine-promo"><div><h3>春季驱虫 × 硬件礼遇</h3><p>绑定设备领解读券 · 点击查看活动</p></div><span class="mine-promo-dots" aria-hidden="true"><i></i><i></i><i></i></span></section><section class="card mine-group"><h3>常用功能</h3><div class="mine-function-grid">${tile('calendar','智能待办','blue')}${tile('file','报告记录','green')}${tile('family','家庭管理','amber')}${tile('headset','在线客服','cyan')}</div></section><section class="card mine-group mine-more"><h3>更多功能</h3><div class="mine-function-grid">${tile('help','常见问题')}${tile('chat','意见反馈')}${tile('bag','商务合作')}${tile('settings','设置')}</div></section></div>`;}

function petsPage(){return `<p class="caption">统一宠物档案。每台摄像头首版关联一只爬宠。</p>${db.pets.map(p=>`<div class="card row"><span class="avatar">${icon('leaf')}</span><div class="grow"><h3>${esc(p.name)}</h3><p class="muted">${esc(p.species)}</p><p class="caption">${db.devices.filter(d=>d.petId===p.id).map(d=>esc(d.name)).join('、')||'尚未关联摄像头'}</p></div></div>`).join('')}${btn('新建爬宠档案','create-pet','secondary full')}`;}
function boundaryPage(title,text,name){return empty(title,text,`<a class="secondary" href="https://czy666-cc.github.io/czl-app3-prototype/home.html" target="_blank" rel="noopener">查看 APP 3.0 原型 ↗</a>`,name);}
function assistantPage(){const ctx=view.context;return boundaryPage('AI 管家','AI 管家沿用 APP 3.0。本次接入原型不展开管家对话流程。','ai')+(ctx?`<div class="card"><h3>摄像头接入上下文</h3><p class="caption">正式接入时，将以下记录带入 APP 3.0 管家。</p><div class="context-card">${esc(ctx.deviceName)} · ${esc(ctx.petName)}<br>${esc(ctx.title)} · ${esc(ctx.date)}<br>${esc(ctx.summary)}</div></div>`:'');}
function wizardPage(){if(!wizard)return '';const w=wizard;let body='';if(w.step==='connecting')return `<div class="card empty"><div class="loading-orb"></div><h3>正在连接摄像头</h3><p>正在检查网络与设备绑定状态…</p>${btn('取消连接','cancel-connect','secondary')}</div>`;
const step=Math.min(Number(w.step)||0,4);const top=`<div class="step-label">步骤 ${step+1} / 5</div><div class="progress">${[0,1,2,3,4].map(i=>`<i class="${i<=step?'on':''}"></i>`).join('')}</div>`;
if(step===0)body=`<h2>选择你的设备</h2><p class="muted small">通过 APP 3.0 统一添加入口接入</p><div class="card">${row('爬宠摄像头<small>视频直播与智能养护</small>','选择','wizard-type','camera')}</div><p class="caption">其他设备类型沿用 APP 3.0。本原型不声明摄像头具备蓝牙发现能力。</p>`;
if(step===1)body=`<h2>让摄像头准备好</h2><div class="card"><p>1. 为摄像头接通电源<br>2. 按设备说明进入配网状态<br>3. 确认手机可连接家庭 Wi-Fi</p></div><form id="prepare-form" class="form"><label>设备识别码<input name="code" value="${esc(w.code||'CZL-CAM-DEMO')}" maxlength="50" required></label><label class="check"><input type="checkbox" name="ready" required>我已按设备说明进入配网状态</label><button class="primary full" type="submit">下一步</button></form><p class="caption">本原型通过输入设备码演示添加流程。</p>`;
if(step===2)body=`<h2>连接家庭 Wi-Fi</h2><p class="caption">请以设备说明支持的 Wi-Fi 频段为准。</p><form id="wifi-form" class="form"><label>Wi-Fi 名称<input name="ssid" value="${esc(w.ssid||'家庭 Wi-Fi')}" maxlength="64" autocomplete="off" required></label><label>Wi-Fi 密码<input name="password" type="password" maxlength="64" autocomplete="new-password" placeholder="输入网络密码" required></label>${w.error?`<p class="form-error" role="alert">${esc(w.error)}</p>`:''}<label>本次连接结果（原型模拟）<select name="outcome"><option value="success">连接成功</option><option value="failure">连接失败</option><option value="timeout">连接超时</option><option value="bound">设备已被绑定</option></select></label><button class="primary full" type="submit">${w.error?'重新连接':'开始连接'}</button></form><p class="caption">密码仅用于表单演示，提交后清空，不写入浏览器存储。</p>`;
if(step===3)body=`<h2>${w.reconfigure?'网络已更新':'连接成功，给它起个名字'}</h2><form id="name-form" class="form"><label>设备名称<input name="name" value="${esc(w.name||'我的爬宠箱')}" maxlength="30" required></label><p class="caption">最多 30 个字符，便于多台设备区分。</p><button type="submit" class="primary full">${w.reconfigure?'保存并返回':'下一步'}</button></form>`;
if(step===4)body=`<h2>关联你的爬宠</h2><p class="caption">稍后关联也可以使用直播和回放。</p>${petChoices(w.petId,'wizard-pet')}${btn('＋ 新建爬宠档案','create-pet','secondary full')}${btn('完成并查看摄像头','finish-bind','primary full',!w.petId?'disabled':'')}${btn('稍后关联，先看直播','skip-bind','text-btn full')}`;
return top+body;}
function petChoices(selected,action){return db.pets.map(p=>btn(`<span class="avatar">${icon('leaf')}</span><span class="grow"><strong>${esc(p.name)}</strong><small style="display:block">${esc(p.species)}</small></span>${selected===p.id?tag('已选择'):''}`,action,'pet-choice'+(selected===p.id?' selected':''),`data-id="${p.id}" aria-pressed="${selected===p.id}"`)).join('');}
let modalReturnFocus=null,clipTimer=null;
function closeQuality(focus=false){$('.quality-popover')?.remove();const trigger=$('[data-action="quality"]');trigger?.setAttribute('aria-expanded','false');if(focus)trigger?.focus();}
function toggleQuality(){const trigger=$('[data-action="quality"]');if($('.quality-popover')){closeQuality(true);return;}const popover=document.createElement('div');popover.className='quality-popover';popover.id='quality-popover';popover.setAttribute('role','group');popover.setAttribute('aria-label','选择画质');popover.innerHTML=['高清','标清'].map(q=>btn(`<span>${q}</span>${dev().quality===q?icon('check'):''}`,'set-quality','quality-option'+(dev().quality===q?' selected':''),`data-value="${q}" aria-pressed="${dev().quality===q}"`)).join('');trigger.setAttribute('aria-expanded','true');trigger.setAttribute('aria-controls','quality-popover');trigger.parentElement.append(popover);popover.querySelector('.selected')?.focus();}
document.addEventListener('click',e=>{if(!e.target.closest('.quality-popover,[data-action="quality"]'))closeQuality();});
document.addEventListener('focusin',e=>{if(!e.target.closest('.quality-popover,[data-action="quality"]'))closeQuality();});
function closeModal(restore=true){clearInterval(clipTimer);clipTimer=null;const had=modal;modal=null;$('#modal-root').innerHTML='';$('#app-content').inert=false;$('#app-header').inert=false;$('#app-nav').inert=false;if(restore&&had&&modalReturnFocus?.isConnected)modalReturnFocus.focus();}
function openModal(type,data={}){clearInterval(clipTimer);clipTimer=null;if(!modal)modalReturnFocus=document.activeElement;modal={type,...data};renderModal();if(type==='event-clip'){syncClipPlayer();clipTimer=setInterval(()=>{if(modal?.type!=='event-clip'||!modal.playing)return;modal.elapsed=Math.min(modal.duration,modal.elapsed+1);if(modal.elapsed===modal.duration)modal.playing=false;syncClipPlayer();},1000);}}
function renderModal(){if(!modal)return;const d=dev(),m=modal;let title='',body='',full=false;
switch(m.type){
case 'switch':title='切换摄像头';body=db.devices.map(x=>row(esc(x.name)+`<small>${esc(pname(x.petId))} · ${x.online?'在线':'离线'}</small>`,x.id===view.deviceId?'当前设备':'','select-device','camera',`data-id="${x.id}"`)).join('');break;
case 'more':title='看护设置';body=row('隐私模式',d.privacy?'已开启':'已关闭','privacy','shield');break;
case 'rename':title='设备名称';body=`<form id="rename-form" class="form"><label>名称<input name="name" value="${esc(d.name)}" maxlength="30" required ${!isOwner(d)?'disabled':''}></label><button class="primary full" ${!isOwner(d)?'disabled':''}>保存</button></form>`;break;
case 'link-pet':title='关联爬宠档案';body=`<p>一台摄像头关联一只爬宠。更换后新报告使用新档案，历史报告保留原归属。</p>${petChoices(d.petId,'choose-pet')}${isOwner(d)?btn('新建爬宠档案','create-pet','secondary full'): '<p>共享成员只能查看关联关系。</p>'}`;break;
case 'create-pet':title='新建爬宠档案';body=`<form id="pet-form" class="form"><label>宠物名字<input name="name" maxlength="20" placeholder="例如 Mochi" required></label><label>物种<input name="species" maxlength="30" placeholder="例如 绿鬣蜥" required></label><button class="primary full" type="submit">保存档案</button></form><p class="caption">复用 APP 宠物档案；保存后可用于摄像头关联。</p>`;break;
case 'network':title='网络状态';body=`<p>设备：${esc(d.name)}<br>状态：${d.online?'在线':'离线'}<br>网络：${esc(d.network)}<br>最后在线：${esc(d.lastSeen)}</p>${btn('重新配网','reconfigure','secondary full',!isOwner(d)?'disabled':'')}`;break;
case 'storage':title='存储卡';body=`<p>${d.sd?'容量：128 GB<br>已用：42.6 GB<br>状态：'+(d.online?'可用':'设备离线，无法读取实时状态'):'未插入存储卡，插入兼容存储卡后可启用本地录像。'}</p><p class="caption">格式化与录制策略本次不开放，避免误解为已接入硬件。</p>`;break;
case 'firmware':title='固件版本';body=`<p>当前版本：${esc(d.firmware)}<br>原型未连接固件服务，无法检查最新版本。</p>`;break;
case 'device-info':title='设备信息';body=`<p>名称：${esc(d.name)}<br>设备编号：${esc(d.id)}<br>品类：爬宠摄像头<br>角色：${isOwner(d)?'拥有者':'共享成员'}</p>`;break;
case 'remove':title=isOwner(d)?'移除这台设备？':'停止接收共享？';body=`<p>${esc(d.name)} 将从此原型账号移除；对应演示事件和报告将不再显示。不会影响其他设备。</p><p>正式产品的解绑与数据保留政策需业务确认。</p>${btn('确认移除','confirm-remove','danger full')}${btn('保留设备','close-modal','secondary full')}`;break;
case 'cancel-bind':title='取消添加设备？';body=`<p>当前配网进度将丢弃，不会生成未完成设备。</p>${btn('取消添加','confirm-cancel','danger full')}${btn('继续添加','close-modal','secondary full')}`;break;
case 'fullscreen':title='全屏预览';full=true;body=`<img src="${IMAGE}" alt="全屏爬宠示例画面"><p>横屏画面演示 · ${esc(d.name)} · 关闭后返回看护</p>`;break;
case 'event-clip':title='事件视频片段';body=`<div class="clip-player"><img src="${IMAGE}" alt="${esc(m.title)}示例画面"><div class="clip-controls">${btn('暂停','clip-toggle','clip-toggle','aria-label="暂停片段"')}<input type="range" min="0" max="${m.duration}" step="1" value="${m.elapsed}" data-change="clip-seek" aria-label="片段播放进度"><span class="clip-time"></span></div></div>`;break;
case 'media':{const item=d.media.find(x=>x.id===m.id);title=item?.kind||'相册';body=item?`<img src="${IMAGE}" style="width:100%;border-radius:12px" alt="${esc(item.kind)}预览"><p>${esc(item.time)} ${item.duration?'· '+item.duration+' 秒':''}</p><p class="caption">${item.kind==='录像'?'手动录像记录演示，使用静态示例帧展示，不包含视频文件。':'截图使用当前原型示例帧。'}</p>${isOwner(d)?btn('删除此记录','delete-media','danger full',`data-id="${item.id}"`):''}`:'<p>记录不存在。</p>';break;}
case 'account':title='账号与隐私';body='<p>摄像头复用 APP 3.0 登录、账号和家庭权限。本原型不模拟第二套登录。</p><p>本地演示数据保存在当前浏览器，可通过场景重置清除。</p>';break;
case 'upgrade-confirm':title='开通当前摄像头';body=`<p>确认将 AI 分析与云录像权益开通到：<strong>${esc(d.name)}</strong>（${esc(d.id)}）。其他设备不受影响。</p><p class="caption">模拟操作，无支付、无自动续费。</p>${btn('确认模拟开通','confirm-activate','primary full')}`;break;
}
$('#modal-root').innerHTML=`<div class="modal-backdrop ${m.type==='event-clip'?'event-player-backdrop':''}"><section class="sheet ${full?'fullscreen-sheet':''} ${m.type==='event-clip'?'event-player-sheet':''}" role="dialog" aria-modal="true" ${m.type==='event-clip'?`aria-label="${esc(pname(m.petId))} ${esc(m.date)} ${esc(m.time)} ${esc(m.title)} · ${view.sample?'示例数据 · ':''}模拟播放"`:'aria-labelledby="sheet-title"'}>${m.type==='event-clip'?ib('close','关闭播放器','close-modal'):`<div class="row between"><h2 id="sheet-title">${title}</h2>${ib('close','关闭弹层','close-modal')}</div>`}${body}</section></div>`;
$('#app-content').inert=true;$('#app-header').inert=true;$('#app-nav').inert=true;$('#modal-root').querySelector('input:not([disabled]),button:not([disabled])')?.focus();}
function syncClipPlayer(){if(modal?.type!=='event-clip')return;const toggle=$('[data-action="clip-toggle"]'),seek=$('[data-change="clip-seek"]');if(!toggle||!seek)return;toggle.textContent=modal.playing?'暂停':modal.elapsed===modal.duration?'重播':'播放';toggle.setAttribute('aria-label',toggle.textContent+'片段');seek.value=modal.elapsed;$('.clip-time').textContent=`00:${String(modal.elapsed).padStart(2,'0')} / 00:${String(modal.duration).padStart(2,'0')}`;}
function openContext(ctx){go('assistant',{context:ctx});}
function reportContext(r,kind='summary'){const k=kinds[kind];return {key:r.id+':'+kind,deviceId:r.deviceId,deviceName:dev().name,petId:r.petId,petName:pname(r.petId),reportId:r.id,date:r.date,title:k?.title||'行为摘要',summary:k?k.ob(r):'进食 '+r.food+' · 活动 '+r.activity+' 分钟'};}
function beginAdd(reconfigure=false){if(reconfigure&&!canManage())return;go('add');wizard={step:reconfigure?2:0,reconfigure,deviceId:reconfigure?view.deviceId:null,name:reconfigure?dev().name:'',ssid:reconfigure?dev().network:'',petId:null};render();}
function finishBind(skip){const w=wizard;if(!w)return;const id='cam-'+Date.now();const d=makeDevice(id,w.name||'我的爬宠箱',skip?null:w.petId,false);d.analysis='insufficient';d.network=w.ssid||'家庭 Wi-Fi';db.devices.push(d);wizard=null;stack=[];view={page:'camera',deviceId:id,section:'care',date:TODAY,scroll:0};save();render();toast('设备已添加'+(skip?'，可稍后关联宠物':''));}
function updateView(change){view.scroll=$('#app-content').scrollTop;Object.assign(view,change);render();}
const scenarios=[['normal','正常 · 多设备'],['empty','无设备'],['unlinked','未关联'],['offline','设备离线'],['privacy','隐私模式'],['unsubscribed','未订阅'],['insufficient','数据不足'],['partial','部分结果可用'],['no-sd','无存储卡'],['no-video','无录像'],['video-error','回放失败']];
function renderScenarios(){$('#scenarios').innerHTML=scenarios.map(([k,t])=>btn(t,'scenario',scenario===k?'active':'',`data-value="${k}" aria-pressed="${scenario===k}"`)).join('');}
function applyScenario(name){snapshotNotice=null;clearTimeout(connectTimer);wizard=null;recording=null;stack=[];closeModal(false);db=seed();scenario=name;const d=db.devices[0];view={page:'camera',deviceId:d.id,section:'care',date:TODAY};switch(name){case'normal':db.devices.forEach(device=>{device.online=true;device.subscription='active';device.analysis='ready';});view.page='home';break;case'empty':db.devices=[];db.events=[];db.reports=[];view.page='home';view.deviceId='';break;case'unlinked':d.petId=null;d.analysis='insufficient';db.events=[];view.section='companion';break;case'offline':d.online=false;break;case'privacy':d.privacy=true;break;case'unsubscribed':d.subscription='inactive';view.section='companion';break;case'insufficient':d.analysis='insufficient';view.section='companion';break;case'partial':db.reports[0].states={food:'ready',water:'insufficient',activity:'ready',region:'insufficient',molt:'insufficient',health:'insufficient',risk:'insufficient'};view.section='companion';break;case'shared':d.role='viewer';d.shared=[{id:'share-1',phone:'13900000002',status:'accepted'}];break;case'no-sd':d.sd=false;view.page='playback';view.source='sd';break;case'no-video':view.page='playback';view.source='cloud';view.playbackState='empty';break;case'video-error':view.page='playback';view.source='cloud';view.playbackState='error';break;}render();}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id,value=el.dataset.value,d=dev();
switch(a){
case'root':root(value);break;case'home':root('home');break;case'back':back();break;case'close-modal':closeModal();break;case'scenario':applyScenario(value);break;
case'open-device':go('camera',{deviceId:id,section:'care',date:TODAY});break;
case'switch-device':openModal('switch');break;
case'select-device':snapshotNotice=null;stopRecording();view={...view,deviceId:id,section:'care',date:TODAY,scroll:0};closeModal();render();break;
case'section':snapshotNotice=null;stopRecording();updateView({section:value,scroll:0});$('#app-content').scrollTop=0;break;
case'messages':go('messages');break;
case'read-all':db.events.forEach(e=>e.read=true);render();toast('已全部标记为已读，异常状态不变');break;
case'event':{const e=db.events.find(e=>e.id===id);if(!e)return;e.read=true;go('event',{eventId:id,deviceId:e.deviceId});break;}
case'resolve-event':if(canManage()){db.events.find(e=>e.id===view.eventId).resolved=true;render();toast('已记录处理结果');}break;
case'ask-event':{const e=db.events.find(e=>e.id===view.eventId);openContext({key:e.id,deviceId:d.id,deviceName:d.name,petId:e.petId,petName:pname(e.petId),eventId:e.id,date:e.time,title:e.title,summary:e.detail});break;}
case'ask-summary':case'ask-report':{const r=reportById(id||view.reportId);if(r)openContext(reportContext(r,a==='ask-report'?view.kind:'summary'));break;}
case'assistant-home':go('assistant',{context:null});break;
case'health':{const c=careData();if(c.states.health==='ready')go('health',{reportId:c.report.id,sample:c.sample,petId:c.report.petId,sampleDate:c.report.date});break;}
case'report':go('report',{reportId:id,reportDate:null,kind:el.dataset.kind||'activity',sample:el.dataset.sample==='true',petId:dev().petId,sampleDate:view.date});break;
case'report-day':changeReportDate(value);break;
case'history':go('history');break;
case'playback':go('playback',{source:value==='cloud'?'cloud':'sd',playing:false,playDate:TODAY,playbackState:'ready',segment:'08:12'});break;
case'event-evidence':{const e=db.events.find(e=>e.id===view.eventId);go('playback',{source:d.online&&d.sd?'sd':'cloud',playDate:e.time.slice(0,10),segment:e.time.slice(11),playing:false,playbackState:'ready'});break;}
case'report-evidence':{const r=reportById(view.reportId);go('playback',{source:d.online&&d.sd?'sd':'cloud',playDate:r.date,segment:kinds[view.kind].time.split('–')[0],playing:false,playbackState:'ready'});break;}
case'segment':updateView({segment:value,playing:true});break;
case'toggle-play':updateView({playing:!view.playing});break;
case'speed':{const speeds=['1.0','1.5','2.0','0.5'];updateView({speed:speeds[(speeds.indexOf(view.speed||'1.0')+1)%4]});break;}
case'retry-playback':updateView({playbackState:'ready'});break;
case'album':go('album');break;
case'snapshot':if(canManage()&&canLive()){d.media.unshift({id:'media-'+Date.now(),kind:'截图',time:new Date().toLocaleTimeString('zh-CN',{hour12:false})});snapshotNotice=d.id;updateView({});}break;
case'record':if(canManage()&&canLive()){if(recording){stopRecording();render();toast('录像记录已加入相册');}else{recording={deviceId:d.id,start:Date.now()};render();toast('开始模拟录像，再次点击结束');}}break;
case'fullscreen':if(canLive())openModal('fullscreen');break;
case'quality':if(canManage()&&canLive())toggleQuality();break;
case'set-quality':if(canManage()&&canLive()&&['高清','标清'].includes(value)){d.quality=value;closeQuality();render();$('[data-action="quality"]')?.focus();}break;
case'event-clip':{const r=detailReport();if(!r||view.page!=='report'||(!view.sample&&d.subscription!=='active'))break;el.focus();openModal('event-clip',{title:el.dataset.title,time:el.dataset.time,date:el.dataset.date,petId:r.petId,deviceId:d.id,elapsed:0,duration:15,playing:true});break;}
case'clip-toggle':if(modal?.type==='event-clip'){if(modal.elapsed===modal.duration)modal.elapsed=0;modal.playing=!modal.playing;syncClipPlayer();}break;
case'media':openModal('media',{id});break;
case'delete-media':if(canManage()){d.media=d.media.filter(m=>m.id!==id);closeModal();render();toast('相册记录已删除');}break;
case'more':openModal('more');break;
case'privacy':if(canManage()&&d.online){snapshotNotice=null;stopRecording();d.privacy=!d.privacy;closeModal();render();}else if(!d.online)toast('设备离线，无法修改隐私模式');break;
case'settings':go('settings');break;
case'rename':case'network':case'storage':case'firmware':case'device-info':openModal(a);break;
case'link-pet':openModal('link-pet');break;
case'choose-pet':if(canManage()){if(d.petId!==id){d.petId=id;d.analysis='insufficient';}closeModal();render();toast('已更新关联，历史报告归属不变');}break;
case'create-pet':if(wizard||view.page==='pets'||canManage())openModal('create-pet',{from:modal?.type||view.page});break;
case'remove-device':openModal('remove');break;
case'confirm-remove':{const removing=d.id;db.devices=db.devices.filter(x=>x.id!==removing);db.events=db.events.filter(e=>e.deviceId!==removing);db.reports=db.reports.filter(r=>r.deviceId!==removing);view.deviceId=db.devices[0]?.id||'';root('home');toast('设备已移除');break;}
case'subscription':go('subscription');break;
case'subscriptions':go('subscriptions');break;
case'device-subscription':go('subscription',{deviceId:id});break;
case'activate':if(canManage())openModal('upgrade-confirm');break;
case'confirm-activate':if(canManage()){d.subscription='active';closeModal();render();toast('已模拟开通 '+d.name+'，其他设备不受影响');}break;
case'pets':go('pets');break;
case'account-help':openModal('account');break;
case'add':beginAdd();break;
case'reconfigure':beginAdd(true);break;
case'wizard-type':wizard.step=1;render();break;
case'cancel-bind':openModal('cancel-bind');break;
case'confirm-cancel':clearTimeout(connectTimer);wizard=null;closeModal();back();break;
case'cancel-connect':clearTimeout(connectTimer);wizard.step=2;wizard.error='连接已取消，可修改网络后重试。';render();break;
case'wizard-pet':wizard.petId=id;render();break;
case'finish-bind':if(wizard?.petId)finishBind(false);break;
case'skip-bind':finishBind(true);break;
}
});
function changeReportDate(date){if(!date||date>TODAY){toast('请选择有效日期');return;}const original=detailReport();const match=db.reports.find(r=>r.deviceId===view.deviceId&&r.petId===original?.petId&&r.date===date);updateView({reportDate:date,reportId:view.sample?view.reportId:match?.id||view.reportId,scroll:0});}
document.addEventListener('input',event=>{if(event.target.dataset.change==='clip-seek'&&modal?.type==='event-clip'){modal.elapsed=Math.max(0,Math.min(modal.duration,Number(event.target.value)||0));if(modal.elapsed===modal.duration)modal.playing=false;syncClipPlayer();}});
document.addEventListener('change',event=>{const action=event.target.dataset.change;if(action==='report-date')changeReportDate(event.target.value);if(action==='date'){const date=event.target.value;if(date&&date<=TODAY)updateView({date,scroll:0});else{event.target.value=view.date;toast('请选择有效日期');}}if(action==='play-date'){const date=event.target.value;if(date&&date<=TODAY)updateView({playDate:date,segment:null,playing:false,playbackState:'ready'});else event.target.value=view.playDate||view.date;}});
function trimmed(form,name){return String(new FormData(form).get(name)||'').trim();}
function formError(form,text){let p=form.querySelector('.form-error');if(!p){p=document.createElement('p');p.className='form-error';p.setAttribute('role','alert');form.append(p);}p.textContent=text;}
document.addEventListener('submit',event=>{const form=event.target;event.preventDefault();if(!form.checkValidity()){form.reportValidity();return;}const d=dev();
switch(form.id){
case'prepare-form':{const code=trimmed(form,'code');if(!code){formError(form,'请输入有效设备识别码');return;}wizard.code=code;wizard.step=2;render();break;}
case'wifi-form':{const ssid=trimmed(form,'ssid');if(!ssid){formError(form,'请输入 Wi-Fi 名称');return;}const outcome=trimmed(form,'outcome');wizard.ssid=ssid;form.elements.password.value='';wizard.error='';wizard.step='connecting';render();clearTimeout(connectTimer);connectTimer=setTimeout(()=>{if(!wizard)return;if(outcome==='success')wizard.step=3;else{wizard.step=2;wizard.error={failure:'连接失败，请检查网络名称和密码后重试。',timeout:'连接超时，请确认设备处于配网状态后重试。',bound:'此设备已被绑定，请联系原拥有者解绑后再添加。'}[outcome];}render();},1200);break;}
case'name-form':{const name=trimmed(form,'name');if(!name){formError(form,'请输入设备名称');return;}wizard.name=name;if(wizard.reconfigure){const x=db.devices.find(x=>x.id===wizard.deviceId);x.network=wizard.ssid;x.online=true;x.name=name;wizard=null;back();toast('网络配置已更新');}else{wizard.step=4;render();}break;}
case'rename-form':if(canManage()){const name=trimmed(form,'name');if(!name){formError(form,'名称不能为空');return;}d.name=name;closeModal();render();}break;
case'pet-form':{const name=trimmed(form,'name'),species=trimmed(form,'species');if(!name||!species){formError(form,'请填写宠物名称和物种');return;}const from=modal?.from,p={id:'pet-'+Date.now(),name,species};db.pets.push(p);if(wizard){wizard.petId=p.id;closeModal();render();}else if(from==='link-pet'&&canManage()){d.petId=p.id;d.analysis='insufficient';closeModal();render();}else{closeModal();render();}break;}

}
save();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if($('.quality-popover')){closeQuality(true);return;}if(modal)closeModal();else if(view.page!=='home')back();}if(event.key==='Tab'&&modal){const elements=[...$('#modal-root').querySelectorAll('button:not([disabled]),input:not([disabled]),select,textarea,a[href]')];const first=elements[0],last=elements.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
window.prototypeState=()=>clone({db,view,stack,wizard,recording});
render();
})();
