const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(e.type!=='css-parsing')errors.push(e)});
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
assert(html.includes(fs.readFileSync(path.join(__dirname,'../script.js'),'utf8')), 'Inline script must match source');
assert(html.includes(fs.readFileSync(path.join(__dirname,'../styles.css'),'utf8')), 'Inline styles must match source');
const dom=new JSDOM(html,{url:'https://prototype.local',runScripts:'dangerously',virtualConsole:vc});
const w=dom.window,doc=w.document,$=s=>{const e=doc.querySelector(s);assert(e,'Missing '+s);return e},all=s=>[...doc.querySelectorAll(s)],click=s=>$(s).click(),act=(a,extra='')=>click(`[data-action="${a}"]${extra}`),state=()=>w.prototypeState(),d=()=>state().db.devices.find(d=>d.id===state().view.deviceId),val=(s,v)=>$(s).value=v,submit=id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})),wait=ms=>new Promise(r=>setTimeout(r,ms)),scenario=s=>act('scenario',`[data-value="${s}"]`),pass=t=>console.log('PASS '+t),text=()=>$('#app-content').textContent;
(async()=>{
assert.equal(state().view.page,'home');assert.equal(all('#app-nav button').length,5);assert(!text().includes('英国短毛猫'));act('open-device');assert.equal(state().view.page,'camera');assert.equal(all('#app-nav button').length,0);assert.equal(all('.section-tabs button').length,2);pass('APP shell, home, camera entry, two sections');
act('section','[data-value="companion"]');for(const t of ['健康评估','AI 多维健康分析','状态解读','健康解读','异常疾病风险识别'])assert(text().includes(t));assert.equal(all('.care-food-grid .care-metric').length,2);assert(!doc.querySelector('.health-dimensions'));assert.equal(all('[data-module]').length,7);assert(!text().includes('晒背'));assert(!w.CAMERA_ORIGINAL.sun);for(const t of ['今日摘要','待关注事件','历史报告','环境适应','环境监测'])assert(!text().includes(t));$('#app-content').scrollTop=220;act('health');assert.equal(state().view.page,'health');for(const t of ['综合健康评分','健康趋势','呼吸道感染','外伤','皮肤溃烂','活力指数','进食规律','体态健康'])assert(text().includes(t));assert(!text().includes('环境适应'));act('back');assert.equal($('#app-content').scrollTop,220);
for(const [kind,label] of [['food','饮水'],['activity','活动次数'],['molt','平均周期']]){act('report',`[data-kind="${kind}"]`);assert(text().includes(label));assert(!text().includes('问问管家'));assert(!text().includes('近 7 日趋势'));act('back');assert.equal(state().view.section,'companion');}
act('report','[data-kind="food"]');act('report-day','[data-value="2026-09-21"]');assert.match(text(),/当天暂无报告/);act('report-day','[data-value="2026-09-22"]');assert.equal(state().view.reportId,'report-2');act('back');assert.equal(state().view.section,'companion');assert.equal($('#app-content').scrollTop,220);pass('original health, AI readings, three behavior details and return context');
scenario('normal');for(const id of ['cam-1','cam-2']){act('open-device',`[data-id="${id}"]`);assert(d().online);assert.equal(d().subscription,'active');act('section','[data-value="companion"]');assert.equal(all('[data-module]').length,7);assert(!text().includes('示例数据'));assert(!text().includes('数据不足'));assert(!text().includes('分析中'));assert(all('[data-result]').every(e=>e.dataset.state==='ready'));act('report','[data-kind="food"]');assert.match(text(),id==='cam-1'?/08:12/:/08:45/);act('back');act('back');}for(const mode of ['unsubscribed','insufficient','partial']){scenario(mode);scenario('normal');assert(state().db.devices.every(d=>d.online&&d.subscription==='active'&&d.analysis==='ready'));assert(state().db.devices.every(d=>state().db.reports.some(r=>r.deviceId===d.id&&r.petId===d.petId&&r.date==='2026-09-23')));}pass('normal scenario gives both devices complete subscribed data and clears exceptional states');
scenario('normal');act('open-device');act('section','[data-value="companion"]');act('report','[data-kind="food"]');$('#app-content').scrollTop=300;const originalView=JSON.stringify(state().view);for(const [i,time,title] of [[0,'08:12','进食'],[1,'13:20','饮水']]){const thumb=all('.event-clip-thumb')[i];thumb.click();assert.match($('.event-player-sheet').getAttribute('aria-label'),new RegExp(time));assert.match($('.clip-player img').alt,new RegExp(title));assert(!doc.querySelector('.clip-event-title'));assert(!doc.querySelector('.clip-note'));assert.equal(JSON.stringify(state().view),originalView);assert.equal($('#app-content').inert,true);await wait(1100);assert(Number($('[data-change="clip-seek"]').value)>0);act('clip-toggle');const elapsed=$('[data-change="clip-seek"]').value;await wait(1100);assert.equal($('[data-change="clip-seek"]').value,elapsed);val('[data-change="clip-seek"]','15');$('[data-change="clip-seek"]').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal($('[data-action="clip-toggle"]').textContent,'重播');act('clip-toggle');assert.equal($('[data-change="clip-seek"]').value,'0');act('close-modal');assert.equal($('#app-content').scrollTop,300);assert.equal(doc.activeElement,thumb);assert.equal($('#app-content').inert,false);}act('back');act('report','[data-kind="activity"]');act('event-clip');assert.match($('.clip-player img').alt,/活动/);doc.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!doc.querySelector('.event-player-sheet'));scenario('unsubscribed');act('report','[data-kind="food"]');act('event-clip');assert.match($('.event-player-sheet').getAttribute('aria-label'),/示例数据/);assert.equal(d().subscription,'inactive');act('close-modal');pass('event thumbnail opens local player, pause/seek/replay, context and focus restoration');
scenario('normal');act('messages');act('event');assert.equal(state().db.events[0].read,true);assert.equal(state().db.events[0].resolved,false);act('back');assert.equal(state().view.page,'messages');act('back');assert.equal(state().view.page,'home');assert.match(text(),/活动较平时减少/);pass('shared event read state without resolving alarm');
scenario('unsubscribed');const events=JSON.stringify(state().db.events);act('subscription');act('activate');act('confirm-activate');assert.equal(d().subscription,'active');assert.equal(JSON.stringify(state().db.events),events);assert.equal(state().db.devices[1].subscription,'active');pass('per-device subscription preserves event state');
scenario('normal');act('open-device');assert(!text().includes('夜视模式'));assert.equal(all('.camera-function-grid button').length,4);act('snapshot');assert.equal(d().media.length,1);assert.match($('.snapshot-feedback').textContent,/截图已保存到相册/);click('.snapshot-feedback [data-action="album"]');assert.equal(state().view.page,'album');assert.equal(all('.gallery button').length,1);act('back');assert(!doc.querySelector('.snapshot-feedback'));act('record');assert(state().recording);act('record');assert.equal(d().media.length,2);act('album');act('media');assert.match($('#modal-root').textContent,/录像/);act('close-modal');act('back');act('privacy');assert.equal(d().privacy,true);assert(!doc.querySelector('.video img'));assert($('[data-action="snapshot"]').disabled);act('switch-device');act('select-device','[data-id="cam-2"]');assert.equal(d().privacy,false);assert.equal(d().media.length,0);pass('snapshot, record, album, privacy cover and device isolation');
scenario('normal');assert(state().db.devices.every(device=>device.online&&device.subscription==='active'));scenario('unsubscribed');act('section','[data-value="care"]');act('playback','[data-value="sd"]');assert.equal(state().view.source,'sd');assert(doc.querySelector('.timeline'));act('back');act('playback','[data-value="cloud"]');assert.match(text(),/云回放需开通设备会员/);assert(!doc.querySelector('.timeline'));act('subscription');act('activate');act('confirm-activate');act('back');assert.equal(state().view.source,'cloud');assert(doc.querySelector('.timeline'));pass('separate local/cloud entries; device membership unlocks cloud playback');
scenario('offline');assert($('[data-action="snapshot"]').disabled);act('playback','[data-value="cloud"]');assert.equal(state().view.source,'cloud');assert.match(text(),/云录像/);assert(!doc.querySelector('[data-action="source"]'));assert.match($('#app-header').textContent,/云回放/);act('back');act('playback','[data-value="sd"]');assert.match($('#app-header').textContent,/本地回放/);assert.match(text(),/设备离线/);pass('offline live disabled, cloud history accessible, SD unavailable');
scenario('shared');assert($('[data-action="snapshot"]').disabled);act('settings');act('rename');assert($('#rename-form button').disabled);act('close-modal');assert(!doc.querySelector('[data-action="privacy"]'));assert.equal(d().privacy,false);act('link-pet');act('choose-pet','[data-id="pet-2"]');assert.equal(d().petId,'pet-1');pass('shared viewer cannot mutate or capture');
scenario('normal');act('open-device');assert(!text().includes('环境监测'));act('section','[data-value="companion"]');assert(!text().includes('环境监测'));assert(!doc.querySelector('[data-value="no-sensor"]'));assert(!doc.querySelector('[data-value="stale"]'));assert(!doc.querySelector('[data-value="alert"]'));scenario('insufficient');assert.match(text(),/数据不足/);assert.equal(all('[data-module]').length,7);assert(!text().includes('95'));assert(doc.querySelector('.heatmap-neutral'));assert(!doc.querySelector('[data-action="scenario"][data-value="pending"]'));assert(!text().includes('分析中'));pass('environment monitoring removed; analysis states preserved');
scenario('normal');act('event','[data-id="event-1"]');assert.equal(state().view.eventId,'event-1');act('event-evidence');assert.equal(state().view.segment,'08:40');act('back');act('resolve-event');assert(state().db.events.find(e=>e.id==='event-1').resolved);pass('behavior event opens correct time and resolves independently');
scenario('normal');act('open-device');act('settings');act('link-pet');act('choose-pet','[data-id="pet-2"]');assert.equal(d().petId,'pet-2');assert(state().db.reports.filter(r=>r.deviceId==='cam-1').every(r=>r.petId==='pet-1'));act('back');act('section','[data-value="companion"]');assert.match(text(),/数据不足/);assert(state().db.reports.filter(r=>r.deviceId==='cam-1').every(r=>r.petId==='pet-1'));assert(!text().includes('95'));pass('relink preserves original historical report identity');
scenario('unsubscribed');const sampleReports=JSON.stringify(state().db.reports);assert.equal(all('[data-module]').length,7);assert.equal(all('[data-module] .tag').filter(x=>x.textContent==='示例数据').length,7);act('report','[data-kind="food"]');assert.match(text(),/示例数据/);assert.match(text(),/08:12/);assert.match(text(),/13:20/);act('back');act('health');assert.match(text(),/示例数据/);assert.match(text(),/健康趋势/);act('back');assert.equal(JSON.stringify(state().db.reports),sampleReports);assert.equal(d().subscription,'inactive');click('[data-module="risk"]');assert.equal(state().view.page,'camera');assert(!doc.querySelector('[data-module="risk"][role="button"]'));pass('sample homepage and details do not grant membership or write reports');
for(const mode of ['insufficient']){scenario(mode);assert.equal(all('[data-module]').length,7);assert(all('[data-action="report"],[data-action="health"]').every(x=>x.disabled));assert(!text().includes('优秀'));assert(!text().includes('暂未识别到明显风险'));assert(!text().includes('状态极佳'));assert(doc.querySelector('.heatmap-neutral'));}
scenario('partial');assert.match($('[data-result="food"]').textContent,/08:12/);assert.match($('[data-result="water"]').textContent,/数据不足/);assert.match($('[data-result="activity"]').textContent,/1小时20分钟/);assert(doc.querySelector('.heatmap-neutral'));assert($('[data-action="health"]').disabled);assert($('[data-kind="molt"]').disabled);act('report','[data-kind="food"]');assert.match(text(),/08:12/);assert(!text().includes('表现正常'));assert(!doc.querySelectorAll('.food-event-item')[0].hidden);assert(doc.querySelectorAll('.food-event-item')[1].hidden);act('back');assert.equal(state().view.section,'companion');pass('module-level insufficient and mixed results with safe details');
scenario('empty');act('add');act('wizard-type');$('#prepare-form input[name="ready"]').checked=true;submit('#prepare-form');val('#wifi-form input[name="password"]','secretPassword');val('#wifi-form select','failure');submit('#wifi-form');await wait(1250);assert.match(text(),/连接失败/);assert.equal(state().db.devices.length,0);assert(!JSON.stringify(state()).includes('secretPassword'));
for(const outcome of ['timeout','bound']){val('#wifi-form input[name="password"]','secretPassword');val('#wifi-form select',outcome);submit('#wifi-form');await wait(1250);assert.match(text(),outcome==='timeout'?/连接超时/:/已被绑定/);}
val('#wifi-form input[name="password"]','secretPassword');submit('#wifi-form');await wait(1250);assert.equal(state().wizard.step,3);val('#name-form input','新增雨林箱');submit('#name-form');act('skip-bind');assert.equal(state().view.page,'camera');assert.equal(d().petId,null);assert.equal(d().name,'新增雨林箱');assert(!w.localStorage.getItem('czl-app3-camera-v1').includes('secretPassword'));assert(!text().includes('关联爬宠档案'));act('section','[data-value="companion"]');act('link-pet');act('create-pet');val('#pet-form input[name="name"]','新爬宠');val('#pet-form input[name="species"]','绿鬣蜥');submit('#pet-form');assert.equal(state().db.pets.find(p=>p.id===d().petId).name,'新爬宠');pass('bind failures/timeout/already bound, retry, optional link and new pet');
act('settings');act('network');act('reconfigure');val('#wifi-form input[name="ssid"]','新网络');val('#wifi-form input[name="password"]','example');submit('#wifi-form');await wait(1250);submit('#name-form');assert.equal(d().network,'新网络');assert.equal(state().view.page,'settings');pass('reconfigure existing device, no duplicate');
act('back');act('back');act('add');act('cancel-bind');act('confirm-cancel');assert.equal(state().db.devices.length,1);assert.equal(state().view.page,'home');pass('cancel add leaves no partial device');
act('open-device');assert(!doc.querySelector('[data-action="sharing"]'));act('quality');act('set-quality','[data-value="标清"]');assert.equal(d().quality,'标清');assert.equal($('.camera-quality').textContent,'标清');act('quality');act('set-quality','[data-value="高清"]');assert.equal(d().quality,'高清');act('settings');assert(!doc.querySelector('[data-action="sharing"]'));act('remove-device');act('confirm-remove');assert.equal(state().db.devices.length,0);assert.equal(state().view.page,'home');pass('quality selection and removal of camera sharing entries');
scenario('video-error');act('retry-playback');assert(doc.querySelector('.timeline'));scenario('no-video');assert.match(text(),/当天没有录像/);assert(!text().includes('可播放时段'));assert(!doc.querySelector('.timeline'));assert(doc.querySelector('.video'));assert($('[data-action="toggle-play"]').disabled);assert.equal(all('[data-action="segment"]').length,0);
for(const source of ['sd','cloud']){scenario('normal');act('open-device');act('playback',`[data-value="${source}"]`);assert(!text().includes('事件标记'));act('toggle-play');val('#play-date','2026-09-20');$('#play-date').dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(state().view.source,source);assert(!text().includes('事件标记'));assert.equal(state().view.playing,false);assert.equal(state().view.segment,null);assert(doc.querySelector('.video'));assert(!doc.querySelector('.video img'));assert($('[data-action="toggle-play"]').disabled);assert($('[data-action="speed"]').disabled);assert.equal(all('[data-action="segment"]').length,0);val('#play-date','2026-09-23');$('#play-date').dispatchEvent(new w.Event('change',{bubbles:true}));assert(doc.querySelector('.video img'));assert(!$('[data-action="toggle-play"]').disabled);assert(all('[data-action="segment"]').length>0);}
scenario('no-sd');assert.match(text(),/未检测到存储卡/);pass('playback error retry, empty and missing SD');
scenario('normal');act('open-device');act('settings');act('rename');val('#rename-form input','<img src=x onerror=alert(1)>');submit('#rename-form');assert(text().includes('<img src=x onerror=alert(1)>'));assert(!doc.querySelector('[onerror]'));pass('user-entered names escaped');
scenario('normal');const legacy=state().db;for(const r of legacy.reports){delete r.water;delete r.region;delete r.healthScore;delete r.risk;}const oldDom=new JSDOM(html,{url:'https://prototype.local',runScripts:'dangerously',virtualConsole:vc,beforeParse(win){win.localStorage.setItem('czl-app3-camera-v1',JSON.stringify(legacy))}});const od=oldDom.window.document;od.querySelector('[data-action="open-device"]').click();od.querySelector('[data-value="companion"]').click();assert.match(od.querySelector('[data-result="water"]').textContent,/数据不足/);assert.match(od.querySelector('[data-result="food"]').textContent,/08:12/);assert(od.querySelector('[data-action="health"]').disabled);assert(od.querySelector('.heatmap-neutral'));oldDom.window.close();pass('legacy reports keep existing results without invented new fields');
const saved=w.localStorage.getItem('czl-app3-camera-v1');const restored=new JSDOM(html,{url:'https://prototype.local',runScripts:'dangerously',virtualConsole:vc,beforeParse(win){win.localStorage.setItem('czl-app3-camera-v1',saved)}});assert.equal(restored.window.prototypeState().view.page,'home');assert.equal(restored.window.prototypeState().db.devices[0].name,d().name);restored.window.close();pass('refresh restores data and returns to home');
const storageBlocked=new JSDOM(html,{url:'https://prototype.local',runScripts:'dangerously',virtualConsole:vc,beforeParse(win){Object.defineProperty(win,'localStorage',{get(){throw new Error('blocked')}})}});assert.equal(storageBlocked.window.prototypeState().view.page,'home');assert.match(storageBlocked.window.document.querySelector('#save-status').textContent,/限制存储/);storageBlocked.window.close();pass('storage unavailable remains usable');
assert.equal(errors.length,0,errors.map(e=>e.message).join('\n'));pass('no JavaScript runtime errors');dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
